### ISSUE TITLE
Rethink you demo player names!

### ISSUE THREAD

**Issue by it-ony** [javierbyte/clashjs#1]
Need a hint?
[src/players/hitler.js](src/players/hitler.js)

**Comment by javierbyte** [comment]
Removing now! Sorry

**Comment by it-ony** [comment]
Try using some character of starwars or your favorite movie. For the demo `deadiest player` explains it also.

**Comment by codingpains** [comment]
Removed the name in 520873f858694004b9546605513e67b4d099d72b
