### ISSUE TITLE
Fail to run the demo

### ISSUE THREAD

**Issue by algorithmdog** [javierbyte/clashjs#29]
Hello. I can't run the demo. When I run "npm run dev", I get these messages:

lilideMacBook-Air:clashjs lili$ npm run dev

> react-hot-boilerplate@1.0.0 dev /Users/lili/code/gameai/clashjs
> webpack-dev-server --progress --profile --colors --hot

 46% 3/5 build modulesevents.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRNOTAVAIL
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1139:19)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:81:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:99:10)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! react-hot-boilerplate@1.0.0 dev: `webpack-dev-server --progress --profile --colors --hot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-hot-boilerplate@1.0.0 dev script 'webpack-dev-server --progress --profile --colors --hot'.
npm ERR! This is most likely a problem with the react-hot-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --progress --profile --colors --hot
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-hot-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lili/code/gameai/clashjs/npm-debug.log

The messages in the npm-debug.log are as follows:
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'predev', 'dev', 'postdev' ]
6 info predev react-hot-boilerplate@1.0.0
7 info dev react-hot-boilerplate@1.0.0
8 verbose unsafe-perm in lifecycle true
9 info react-hot-boilerplate@1.0.0 Failed to exec dev script
10 verbose stack Error: react-hot-boilerplate@1.0.0 dev: `webpack-dev-server --progress --profile --colors --hot`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid react-hot-boilerplate@1.0.0
12 verbose cwd /Users/lili/code/gameai/clashjs
13 error Darwin 14.5.0
14 error argv "node" "/usr/local/bin/npm" "run" "dev"
15 error node v0.12.4
16 error npm  v2.10.1
17 error code ELIFECYCLE
18 error react-hot-boilerplate@1.0.0 dev: `webpack-dev-server --progress --profile --colors --hot`
18 error Exit status 1
19 error Failed at the react-hot-boilerplate@1.0.0 dev script 'webpack-dev-server --progress --profile --colors --hot'.
19 error This is most likely a problem with the react-hot-boilerplate package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     webpack-dev-server --progress --profile --colors --hot
19 error You can get their info via:
19 error     npm owner ls react-hot-boilerplate
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

Could some can tell me how to fix this problem

**Comment by javierbyte** [comment]
@algorithmdog I'll take a look, thanks!

**Comment by javierbyte** [comment]
@algorithmdog are you using node 0.12.4? can you please try with 4+?

**Comment by algorithmdog** [comment]
@javierbyte Ok, I will try. Thank you for your timely replay
